engine:
  index_path: "imaged.db"
  num_workers: 4
  use_gpu: false
  log_level: "info"
  max_memory_mb: 1024

hashing:
  compute_ahash: true
  compute_phash: true
  compute_dhash: true
  compute_whash: false
  hash_size: 8

quality:
  detailed_analysis: true
  sharpness_threshold: 0.1
  noise_threshold: 0.3
  min_exposure: 0.1
  max_exposure: 0.9
  min_contrast: 0.2

similarity:
  min_similarity: 0.8
  use_feature_vectors: false
  ahash_weight: 0.2
  phash_weight: 0.4
  dhash_weight: 0.3
  whash_weight: 0.1

scanner:
  supported_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".webp"
    - ".tiff"
    - ".bmp"
  exclude_dirs:
    - ".git"
    - ".svn"
    - "node_modules"
    - "__pycache__"
  max_file_size_mb: 500
  follow_symlinks: false